name: Build Kernel

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev bc

      - name: Build Kernel and Modules
        run: |
          # استخدام ملف الـ config الموجود في المستودع
          make olddefconfig
          # بناء النواة والموديولات
          make -j$(nproc)
          make modules_install INSTALL_MOD_PATH=./out/modules
          # تجهيز الهيدرز
          make headers_install INSTALL_HDR_PATH=./out/headers
          # تجهيز ملف النواة والماب
          cp arch/x86/boot/bzImage ./out/
          cp System.map ./out/
          # ضغط الموديولات لتسهيل تحميلها
          tar -czf ./out/modules.tar.gz -C ./out/modules .

      - name: Prepare Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kernel-full-package
          path: ./out/
